stages:
  - test
  - run
  - doc
  - pub

variables:
  SSH_SERVER_HOSTKEYS: lxplus ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAxDFr+wqtWq0sDCGO2LfsMKVwmhsdXC9TYCVq6HoEBEOXFUgc/3Kf2NooJTgHRQ9h7ZEhx8vdZgoy2+XTwJvqYzx9epIC/gC/ts2z47TvK+FAAkpci5V/5zc9pu8fEYCEwrP+FgF7d3k2ivmZ95Mi/Hhmd9xzxAdps6bpJN19EA0=

#############
# Run tests #
#############
run_test:
  stage: test
  tags:
    - docker
  image: clicdp/slc6-base
  script:
    - source .gitlab-ci.d/init_python3.sh
    - pip3 install --user pandas
    - pip3 install --user matplotlib
    - pip3 install --user IPython
    - pip3 install --user tabulate
    - pip3 install --user pytest
    - export PATH=$PATH:~/.local/bin
    - yum -y install tk
    - source .gitlab-ci.d/disable_Xserver.sh
    - cd analysis
    - pytest

################
# Run analysis #
################
run_ex:
  stage: run
  tags:
    - docker
  image: clicdp/slc6-base
  script:
    - source .gitlab-ci.d/init_python3.sh
    - pip3 install --user pandas
    - pip3 install --user matplotlib
    - pip3 install --user IPython
    - pip3 install --user tabulate
    - yum -y install tk
    - source .gitlab-ci.d/disable_Xserver.sh
    - cd analysis
    - python3 plot_data.py
    - python3 compare_data.py
    - python3 extract_xsec.py
  artifacts:
    paths:
      - analysis/fig/fig_ex
      - analysis/tex/tex_ex
    expire_in: 1 hour


run_full:
  stage: run
  only:
    - master
  tags:
    - docker
  image: clicdp/slc6-base
  before_script:
    - mkdir -p ~/.ssh
    - 'echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
    # tell SSH to forward Kerberos credentials so lxplus can access AFS/EOS on behalf of the user
    - 'echo -e "Host *\n\tGSSAPIDelegateCredentials yes\n\tGSSAPITrustDNS yes\n\n" > ~/.ssh/config'
  script:
    - echo "${KRB_PASSWORD}" | kinit ${KRB_USERNAME}@CERN.CH
    - klist
    - source .gitlab-ci.d/copy_full_analysis_files.sh ${KRB_USERNAME}
    - source .gitlab-ci.d/init_python3.sh
    - pip3 install --user pandas
    - pip3 install --user matplotlib
    - pip3 install --user IPython
    - pip3 install --user tabulate
    - yum -y install tk
    - source .gitlab-ci.d/disable_Xserver.sh
    - cd analysis
    - python3 plot_data.py
    - python3 extract_xsec.py
  artifacts:
    paths:
      - analysis/fig/fig_ex
      - analysis/tex/tex_ex
    expire_in: 1 weeks


run_comp:
  stage: run
  only:
    - master
  tags:
    - docker
  image: clicdp/slc6-base
  before_script:
    - mkdir -p ~/.ssh
    - 'echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
    # tell SSH to forward Kerberos credentials so lxplus can access AFS/EOS on behalf of the user
    - 'echo -e "Host *\n\tGSSAPIDelegateCredentials yes\n\tGSSAPITrustDNS yes\n\n" > ~/.ssh/config'
  script:
    - echo "${KRB_PASSWORD}" | kinit ${KRB_USERNAME}@CERN.CH
    - klist
    - source .gitlab-ci.d/copy_comparison_files.sh ${KRB_USERNAME}
    - source .gitlab-ci.d/init_python3.sh
    - pip3 install --user pandas
    - pip3 install --user matplotlib
    - pip3 install --user IPython
    - pip3 install --user tabulate
    - yum -y install tk
    - source .gitlab-ci.d/disable_Xserver.sh
    - cd analysis
    - python3 compare_data.py
  artifacts:
    paths:
      - analysis/fig/fig_ex
      - analysis/tex/tex_ex
    expire_in: 1 weeks


############
# Document #
############

doc_test:
  stage: doc
  except:
    - master
  tags:
    - docker
  dependencies:
    - run_ex
  image: clicdp/fedora-latex
  script:
    - cd doc
    - pdflatex presentation.tex
    - pdflatex presentation.tex
    - pdflatex comparison.tex
    - pdflatex comparison.tex
    # - pdflatex -interaction=nonstopmode presentation.tex
  artifacts:
    paths:
      - doc/*.pdf
    expire_in: 1 weeks


doc_full:
  stage: doc
  only:
    - master
  tags:
    - docker
  dependencies:
    - run_full
    - run_comp
  image: clicdp/fedora-latex
  script:
    - cd doc
    - pdflatex presentation.tex
    - pdflatex presentation.tex
    - pdflatex comparison.tex
    - pdflatex comparison.tex
    # - pdflatex -interaction=nonstopmode presentation.tex
  artifacts:
    paths:
      - doc/*.pdf
    expire_in: 4 weeks


###########
# Publish #
###########

pub_test:
  stage: pub
  except:
    - master
  tags:
    - docker
  dependencies:
    - doc_test
  image: clicdp/fedora-latex
  script:
    - cd doc
    - ls

pub_full:
  stage: pub
  only:
    - master
  tags:
    - docker
  dependencies:
    - doc_full
  image: clicdp/fedora-latex
  script:
    - cd doc
    - ls
