stages:
  - run
  - documentation

#############
# Run tests #
#############
run_test:
  stage: run
  tags:
    - docker
  script:
    - ls -l /afs/cern.ch/work/a/amaier/CLIC/csv/2094.csv
    - head /afs/cern.ch/work/a/amaier/CLIC/csv/2094.csv
    - source .gitlab-ci.d/init_python3.sh
    - pip3 install --user pandas
    - pip3 install --user matplotlib
    - pip3 install --user IPython
    - pip3 install --user tabulate
    - yum -y install tk
    - source .gitlab-ci.d/disable_Xserver.sh
    - cd analysis
    - python3 plot_data.py
  artifacts:
    paths:
      - analysis/fig/
      - analysis/tex/
    expire_in: 1 hour

#################
# Documentation #
#################

presentation:
  stage: documentation
  tags:
    - docker
  dependencies:
    - run_test
  image: clicdp/fedora-latex
  script:
    - cd doc
    - pdflatex presentation.tex
    - pdflatex presentation.tex
    # - pdflatex -interaction=nonstopmode presentation.tex
  artifacts:
    paths:
      - doc/*.pdf
    expire_in: 1 day
