stages:
  - test

#############
# Run tests #
#############
run_test:
  stage: test
  tags:
    - docker
  script:
    - source .gitlab-ci.d/init_python3.sh
    - pip3 install --user pandas
    - pip3 install --user matplotlib
    - yum -y install tk
    - cd analysis
    - python3 plot_data.py
