stages:
  - run

#############
# Run tests #
#############
run_test:
  stage: run
  tags:
    - docker
  script:
    - source .gitlab-ci.d/init_python3.sh
    - pip3 install --user pandas
    - pip3 install --user matplotlib
    - pip3 install --user IPython
    - yum -y install tk
    - source .gitlab-ci.d/disable_Xserver.sh
    - cd analysis
    - python3 plot_data.py
