stages:
  - run
  - doc

#############
# Run tests #
#############
run_test:
  stage: run
  tags:
    - docker
  script:
    - source .gitlab-ci.d/init_python3.sh
    - pip3 install --user pandas
    - pip3 install --user matplotlib
    - pip3 install --user IPython
    - pip3 install --user tabulate
    - yum -y install tk
    - source .gitlab-ci.d/disable_Xserver.sh
    - cd analysis
    - python3 plot_data.py
  artifacts:
    paths:
      - analysis/fig/
      - analysis/tex/
    expire_in: 1 hour


run_full:
  stage: run
  only:
    - master
  tags:
    - docker
  variables:
    SSH_SERVER_HOSTKEYS: lxplus ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAxDFr+wqtWq0sDCGO2LfsMKVwmhsdXC9TYCVq6HoEBEOXFUgc/3Kf2NooJTgHRQ9h7ZEhx8vdZgoy2+XTwJvqYzx9epIC/gC/ts2z47TvK+FAAkpci5V/5zc9pu8fEYCEwrP+FgF7d3k2ivmZ95Mi/Hhmd9xzxAdps6bpJN19EA0=
  before_script:
    - mkdir -p ~/.ssh
    - 'echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
    # tell SSH to forward Kerberos credentials so lxplus can access AFS/EOS on behalf of the user
    - 'echo -e "Host *\n\tGSSAPIDelegateCredentials yes\n\tGSSAPITrustDNS yes\n\n" > ~/.ssh/config'
  script:
    - echo "${KRB_PASSWORD}" | kinit ${KRB_USERNAME}@CERN.CH
    - klist
    - ssh ${KRB_USERNAME}@lxplus "ls /afs/cern.ch/work/a/amaier/CLIC/csv"
    - scp ${KRB_USERNAME}@lxplus:/afs/cern.ch/work/a/amaier/CLIC/csv/3249.csv example_data/3249.csv
    - scp ${KRB_USERNAME}@lxplus:/afs/cern.ch/work/a/amaier/CLIC/csv/3246.csv example_data/3246.csv
    - scp ${KRB_USERNAME}@lxplus:/afs/cern.ch/work/a/amaier/CLIC/csv/5572.csv example_data/5572.csv
    - scp ${KRB_USERNAME}@lxplus:/afs/cern.ch/work/a/amaier/CLIC/csv/2094.csv example_data/2094.csv
    - scp ${KRB_USERNAME}@lxplus:/afs/cern.ch/work/a/amaier/CLIC/csv/4034.csv example_data/4034.csv
    - scp ${KRB_USERNAME}@lxplus:/afs/cern.ch/work/a/amaier/CLIC/csv/5527.csv example_data/5527.csv
    - scp ${KRB_USERNAME}@lxplus:/afs/cern.ch/work/a/amaier/CLIC/csv/5594.csv example_data/5594.csv
    - source .gitlab-ci.d/init_python3.sh
    - pip3 install --user pandas
    - pip3 install --user matplotlib
    - pip3 install --user IPython
    - pip3 install --user tabulate
    - yum -y install tk
    - source .gitlab-ci.d/disable_Xserver.sh
    - cd analysis
    - python3 plot_data.py
  artifacts:
    paths:
      - analysis/fig/
      - analysis/tex/
    expire_in: 1 hour


#################
# Documentation #
#################

doc_test:
  stage: doc
  tags:
    - docker
  dependencies:
    - run_test
  image: clicdp/fedora-latex
  script:
    - cd doc
    - pdflatex presentation.tex
    - pdflatex presentation.tex
    # - pdflatex -interaction=nonstopmode presentation.tex
  artifacts:
    paths:
      - doc/*.pdf
    expire_in: 1 day

doc_full:
  stage: doc
  only:
    - master
  tags:
    - docker
  dependencies:
    - run_full
  image: clicdp/fedora-latex
  script:
    - cd doc
    - pdflatex presentation.tex
    - pdflatex presentation.tex
    # - pdflatex -interaction=nonstopmode presentation.tex
  artifacts:
    paths:
      - doc/*.pdf
    expire_in: 1 day